-- NOTICE:
-- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
-- AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
-- IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
-- ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE 
-- LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
-- CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
-- SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
-- INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
-- CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
-- ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
-- POSSIBILITY OF SUCH DAMAGE.
-- 
-- read LICENSE.md for more informations.

_G.FBMAKE_VERSION_MAJOR = 0
_G.FBMAKE_VERSION_MINOR = 2
_G.FBMAKE_VERSION_PATCH = 0

_G.FBMAKE_VERSION = FBMAKE_VERSION_MAJOR .. '.' .. FBMAKE_VERSION_MINOR .. '.' .. FBMAKE_VERSION_PATCH 

function _G.require_fbmake_version(maj, min, patch)
	patch = patch or 0
	if type(maj) == 'string' then
		local v = maj:split('.', true)
		maj = tonumber(v[1])
		min = tonumber(v[2])
		if (#v >= 3) then
			patch = tonumber(v[3])
		end
	end
	if (maj > FBMAKE_VERSION_MAJOR or
			(maj == FBMAKE_VERSION_MAJOR and min > FBMAKE_VERSION_MINOR) or
			(maj == FBMAKE_VERSION_MAJOR and min == FBMAKE_VERSION_MINOR and patch > FBMAKE_VERSION_PATCH)) then
		error("FBMake version " .. FBMAKE_VERSION ..
			' is lower than required version ' .. maj ..'.' .. min .. '.' .. patch
		)
	end
end
